const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('app.js','utf8');
const program=source.slice(source.indexOf('function ensureFitness'),source.indexOf('const KEGEL_LEVELS'));
const context={state:{fitness:{existing:'kept',kegel:{history:[]}}},clone:x=>JSON.parse(JSON.stringify(x)),localDateKey:x=>typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)?x:''};
vm.createContext(context);vm.runInContext(program+';this.api={ensureFitness,importLegacyGymData};',context);
context.api.ensureFitness();
const gym=context.state.fitness.gym;
assert.equal(context.state.fitness.existing,'kept');
assert.equal(gym.workouts.length,1);
assert.equal(gym.workouts[0].id,'gym-legacy-2026-03-31');
assert.equal(gym.workouts[0].date,'2026-03-31');
assert.deepEqual(Array.from(gym.workouts[0].exercises[0].sets,s=>[s.distanceKm,s.durationSeconds]),[[4,1380]]);
assert.equal(gym.workouts[0].exercises.find(x=>x.exerciseId==='gym-ex-neck-back').sets.length,0);
assert.equal(gym.legacyDrafts.length,4);
assert.equal(gym.legacyDrafts.every(x=>x.date===null),true);
const combo=gym.legacyDrafts.find(x=>x.id==='gym-draft-biceps-triceps');
assert.equal(combo.sets.every(x=>x.weightKg===undefined),true);
const squat=gym.legacyDrafts.find(x=>x.id==='gym-draft-squat');
assert.deepEqual(Array.from(squat.sets,s=>[s.weightKg,s.reps,s.calculated||false]),[[70,20,false],[90,15,true]]);
context.api.ensureFitness();
assert.equal(gym.workouts.length,1);assert.equal(gym.exercises.length,7);assert.equal(gym.legacyDrafts.length,4);
console.log('V0.24.4 gym migration and historical-data scenarios passed');
